DROP TABLE IF EXISTS subjects;
CREATE TABLE subjects(
   subject_id           INTEGER  NOT NULL PRIMARY KEY 
  ,subject_name         VARCHAR(100) NOT NULL
  ,subject_name_english VARCHAR(100) NOT NULL
  ,stage                VARCHAR(30) NOT NULL
  ,semester             VARCHAR(30) NOT NULL
  ,department           VARCHAR(100) NOT NULL
  ,max_theory_mark      INTEGER  NOT NULL
  ,max_lab_mark         INTEGER  NOT NULL
  ,max_semester_mark    INTEGER  NOT NULL
  ,max_final_exam       INTEGER  NOT NULL
  ,credits              INTEGER  NOT NULL
  ,active               VARCHAR(10) NOT NULL
  ,ministerial          VARCHAR(10) NOT NULL
  ,created_at timestamp(0) with time zone NOT NULL DEFAULT NOW()
);
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1101,'بايولوجي انسان','Human Biology','الاولى','الاول','فرع العلوم المختبرية السريرية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1102,'مباديء صيدلة','Priniciples of Pharmacy Practice','الاولى','الاول','فرع الصيدلانيات',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1103,'كيمياء تحليلية','Analytical Chemsitry','الاولى','الاول','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1104,'مصطلحات طبية','Medical Terminology','الاولى','الاول','فرع العلوم المختبرية السريرية',30,0,30,70,1,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1105,'رياضيات واحصاء','Mathmatics and Biostatistics','الاولى','الاول','فرع العلوم المختبرية السريرية',30,0,30,70,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1108,'الديمقراطية وحقوق الانسان','Democracy and Human Rights','الاولى','الاول','فرع العلوم المختبرية السريرية',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1201,'تشريح انسان','Human Anatomy','الاولى','الثاني','فرع العلوم المختبرية السريرية',20,20,40,60,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1202,'حسابات صيدلانية','Pharmaceutical Calculations','الاولى','الثاني','فرع الصيدلانيات',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1203,'فيزياء طبية','Medical Physics','الاولى','الثاني','فرع العلوم المختبرية السريرية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1204,'كيمياء عضوية I','Organic Chemistry I','الاولى','الثاني','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1205,'انسجة','Histology','الاولى','الثاني','فرع العلوم المختبرية السريرية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (1206,'حاسبات I','Computer Sciences I','الاولى','الثاني','فرع العلوم المختبرية السريرية',20,20,40,60,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2101,'كيمياء عضوية II','Organic Chemistry II','الثانية','الاول','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2102,'احياء مجهرية I','Microbiology I','الثانية','الاول','فرع العلوم المختبرية السريرية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2103,'صيدلة فيزياوية I','Physical Pharmacy I','الثانية','الاول','فرع الصيدلانيات',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2104,'فسلجة I','Physiology I','الثانية','الاول','فرع الادوية والسموم',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2105,'حاسبات II','Computer Sciences II','الثانية','الاول','فرع العلوم المختبرية السريرية',0,30,30,70,1,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2106,'جرائم البعث','Al-Baath Crimes','الثانية','الاول','فرع العلوم المختبرية السريرية',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2201,'كيمياء عضوية III','Organic Chemistry III','الثانية','الثاني','فرع الكيمياء الصيدلانية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2202,'احياء مجهرية II','Microbiology II','الثانية','الثاني','فرع العلوم المختبرية السريرية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2203,'صيدلة فيزياوية II','Physical Pharmacy II','الثانية','الثاني','فرع الصيدلانيات',20,20,40,60,4,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2204,'فسلجة II','Physiology II','الثانية','الثاني','فرع الادوية والسموم',20,20,40,60,4,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (2205,'عقاقير I','Pharmacognosy','الثانية','الثاني','فرع العقاقير والنباتات الطبية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3101,'كيمياء صيدلانية لاعضوية','Inorganic Pharmaceutical Chemistry','الثالثة','الاول','فرع الكيمياء الصيدلانية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3102,'عقاقير II','Pharmacognosy II','الثالثة','الاول','فرع العقاقير والنباتات الطبية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3103,'صيدلة تكنولوجية I','Pharmaceutical Technology I','الثالثة','الاول','فرع الصيدلانيات',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3104,'كيمياء حياتية I','Biochemistry I','الثالثة','الاول','فرع العلوم المختبرية السريرية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3105,'فسلجة مرضية','Pathphysiology','الثالثة','الاول','فرع العلوم المختبرية السريرية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3201,'كيمياء صيدلانية عضوية I','Organic Pharmaceutical Chemistry I','الثالثة','الثاني','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3202,'ادوية I','Pharmacology I','الثالثة','الثاني','فرع الادوية والسموم',30,0,30,70,3,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3203,'صيدلة تكنولوجية II','Pharmaceutical Technology II','الثالثة','الثاني','فرع الصيدلانيات',20,20,40,60,4,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3204,'كيمياء حياتية II','Biochemistry II','الثالثة','الثاني','فرع العلوم المختبرية السريرية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3205,'عقاقير III','Pharmacognosy III','الثالثة','الثاني','فرع العقاقير والنباتات الطبية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (3206,'اخلاقيات الصيدلة','Pharmacy Ethics','الثالثة','الثاني','فرع الصيدلة السريرية',30,0,30,70,1,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4101,'ادوية II','Pharmacology II','الرابعة','الاول','فرع الادوية والسموم',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4102,'كيمياء صيدلانية عضوية II','Organic Pharmaceutical Chemistry II','الرابعة','الاول','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4103,'صيدلة سريرية I','Clinical Pharmacy I','الرابعة','الاول','فرع الصيدلة السريرية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4104,'صيدلة حياتية','Biopharmaceutics','الرابعة','الاول','فرع الصيدلانيات',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4105,'صحة عامة','Public Health','الرابعة','الاول','فرع الصيدلة السريرية',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4201,'ادوية III','Pharmacology III','الرابعة','الثاني','فرع الادوية والسموم',30,0,30,70,2,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4202,'كيمياء صيدلانية عضوية III','Organic Pharmaceutical Chemistry III','الرابعة','الثاني','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4203,'صيدلة سريرية II','Clinical Pharmacy II','الرابعة','الثاني','فرع الصيدلة السريرية',20,20,40,60,3,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4204,'سموم عامة','General Toxicology','الرابعة','الثاني','فرع الادوية والسموم',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4205,'صيدلة صناعية I','Industrial Pharmacy I','الرابعة','الثاني','فرع الصيدلانيات',20,20,40,60,4,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (4206,'مهارات تواصل','Communication Skills','الرابعة','الثاني','فرع الصيدلة السريرية',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5101,'كيمياء صيدلانية عضوية IV','Organic Pharmaceutical Chemistry IV','الخامسة','الاول','فرع الكيمياء الصيدلانية',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5102,'صيدلة صناعية  II','Industrial Pharmacy II','الخامسة','الاول','فرع الصيدلانيات',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5103,'علاجيات تطبيقية I','Applied Therapeutics I','الخامسة','الاول','فرع الصيدلة السريرية',30,0,30,70,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5104,'كيمياء سريرية','Clinical Chemistry','الخامسة','الاول','فرع العلوم المختبرية السريرية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5105,'تدريب مختبرات سريرية','Clinical Laboratory Training','الخامسة','الاول','فرع العلوم المختبرية السريرية',0,40,40,60,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5106,'سموم سريرية','Clinical Toxicology','الخامسة','الاول','فرع الادوية والسموم',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5107,'مشروع التخرج','Graduation Research','الخامسة','الاول','فرع العلوم المختبرية السريرية',100,0,100,0,1,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5201,'اقتصاد دوائي','Pharmacoeconomics','الخامسة','الثاني','فرع الصيدلة السريرية',30,0,30,70,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5202,'علاجيات تطبيقية II','Applied Therapeutics II','الخامسة','الثاني','فرع الصيدلة السريرية',30,0,30,70,2,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5203,'TDM','TDM','الخامسة','الثاني','فرع الصيدلة السريرية',20,20,40,60,3,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5204,'تحليلات صيدلانية متقدمة','Advanced Pharmaceutical Analysis','الخامسة','الثاني','فرع الكيمياء الصيدلانية',20,20,40,60,4,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5205,'تدريب مستشفيات','Hospital Training','الخامسة','الثاني','فرع العلوم المختبرية السريرية',0,40,40,60,2,'نعم','لا');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5206,'تصميم جرع','Dosage Form Design','الخامسة','الثاني','فرع الصيدلانيات',30,0,30,70,2,'نعم','نعم');
INSERT INTO subjects(subject_id,subject_name,subject_name_english,stage,semester,department,max_theory_mark,max_lab_mark,max_semester_mark,max_final_exam,credits,active,ministerial) VALUES (5207,'تقنيات حياتية','Biotechnology','الخامسة','الثاني','فرع الصيدلانيات',30,0,30,70,1,'نعم','لا');
